owner: cloudover
repo: upptime

sites:
  - name: cloudover.io
    url: https://cloudover.io
  - name: dinemic.io
    url: https://dinemic.io
  - name: himalaje
    url: https://himalaje.eu
  - name: Gitlab
    url: https://gitlab.cloudover.io

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** tests"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
